services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules #anonymous volume to avoid overwriting node_modules

#devcontainer would solve the issue here as well.
